/** نصوص وأنواع ومساعدات لوحة المنشأة — وحدة واحدة مشتركة. */
export type FacilitySearch = { tab?: string };

export const TXT = {
  ar: {
    loading: "جارٍ التحميل...",
    verified: " · منشأة موثّقة",
    unverified: " · بانتظار التوثيق",
    applicants: "المتقدمون",
    trial: "تجربة مجانية",
    expired: "منتهية",
    endsAt: (d: string) => `تنتهي في ${d}`,
    activeSub: "الاستخدام التجريبي متاح",
    activeJobsCount: (a: number, b: number) => `الوظائف النشطة ${a}/${b}`,
    activeShiftsCount: (a: number, b: number) => `المناوبات المتاحة ${a}/${b}`,
    publish: "نشر جديد",
    verifyNow: "أكمل توثيق منشأتك",
    verifyBody: "ارفع المستندات المطلوبة ليظهر للكوادر أن منشأتك موثّقة.",
    newApplicants: "طلبات جديدة",
    unreadMessages: "رسائل غير مقروءة",
    activeJobs: "وظائف نشطة",
    openShifts: "مناوبات متاحة",
    searchesRemaining: (n: number) => `${n} عملية بحث متبقية`,
    loadFailed: "تعذّر تحميل بيانات المنشأة.",
    retry: "إعادة المحاولة",
    tabJobs: (n: number) => `الوظائف (${n})`,
    tabShifts: (n: number) => `المناوبات (${n})`,
    tabNewJob: "نشر وظيفة",
    tabNewShift: "نشر مناوبة",
    applicantsCount: (n: number) => `${n} متقدم`,
    published: "منشورة",
    closed: "مغلقة",
    close: "إغلاق",
    republish: "إعادة نشر",
    noJobs: "لم تنشر وظائف بعد.",
    perHour: "/ساعة",
    open: "متاحة",
    bookedStatus: "محجوزة",
    noShifts: "لا مناوبات منشورة.",
    view: "عرض",
    cancelledStatus: "ملغاة",
    cancelShift: "إلغاء",
    shiftCancelled: "تم إلغاء المناوبة",
    confirmCloseTitle: "إغلاق هذه الوظيفة؟",
    confirmCloseDesc: "لن تظهر للباحثين ولن تستقبل طلبات جديدة. يمكنك إعادة نشرها لاحقاً.",
    confirmCloseCta: "نعم، أغلقها",
    confirmCancelShiftTitle: "إلغاء هذه المناوبة؟",
    confirmCancelShiftDesc: "سيتم إلغاء المناوبة وإخفاؤها عن الباحثين، ولا يمكن التراجع.",
    confirmCancelBookedShiftDesc:
      "هذه المناوبة محجوزة. الإلغاء سيلغي حجز المختص ويصله إشعار بذلك، ولا يمكن التراجع.",
    confirmCancelShiftCta: "نعم، ألغِها",
    moreActions: "إجراءات أخرى",
    tabAll: (n: number) => `الكل (${n})`,
    invite: "دعوة مختصين",
    confirmCompleteTitle: "إنهاء المناوبة؟",
    confirmCompleteDesc: "سيتم تسجيل المناوبة كمنتهية ولا يمكن التراجع.",
    confirmCompleteCta: "إنهاء المناوبة",

    // Facility form
    registerTitle: "سجّل منشأتك",
    registerSub: "دقيقة واحدة وتستطيع نشر أول وظيفة أو مناوبة.",
    facilityName: "اسم المنشأة",
    facilityType: "نوع المنشأة",
    hospital: "مستشفى",
    clinic: "عيادة",
    polyclinic: "مجمع طبي",
    pharmacy: "صيدلية",
    lab: "مختبر / أشعة",
    country: "الدولة",
    pickCountry: "اختر الدولة",
    city: "المدينة",
    website: "الموقع الإلكتروني",
    description: "نبذة عن المنشأة",
    saving: "جارٍ الحفظ...",
    createFacility: "إنشاء ملف المنشأة",
    createdFacility: "تم إنشاء ملف المنشأة",
    saveFailed: "تعذّر الحفظ",
    nameRequired: "أدخل اسم المنشأة",
    countryRequired: "اختر الدولة",
    cityRequired: "أدخل المدينة",
    // Job form
    jobTitle: "المسمى الوظيفي",
    specialty: "التخصص",
    pickSpecialty: "اختر التخصص",
    employmentType: "نوع التوظيف",
    minExperience: "أقل خبرة مطلوبة (سنوات)",
    vacancies: "عدد الشواغر",
    vacanciesHint: "كم مرشحاً تريد توظيفه لهذه الوظيفة؟ تُقفل الوظيفة تلقائياً عند اكتمال العدد.",
    salaryFrom: "الراتب من",
    salaryTo: "الراتب إلى",
    currency: "العملة",
    requiredLicense: "ترخيص مطلوب",
    licensePlaceholder: "بدون / اختر الدولة",
    jobDesc: "وصف الوظيفة والمتطلبات",
    publishing: "جارٍ النشر...",
    publishJob: "نشر الوظيفة",
    jobPublished: "تم نشر الوظيفة",
    publishFailed: "تعذّر النشر",
    subExpiredJob: "النشر متوقف مؤقتاً لهذا الحساب — تواصل مع الدعم للمساعدة",
    quotaReachedJob: "وصلت حد الوظائف النشطة في النسخة التجريبية — أغلق وظيفة نشطة للنشر من جديد",
    titleMin: "أدخل المسمى الوظيفي",
    descMin: "اكتب وصفاً لا يقل عن ٢٠ حرفاً",
    salaryMaxGt: "الحد الأعلى للراتب يجب أن يكون أكبر",
    // Shift form
    shiftTitle: "عنوان المناوبة",
    shiftTitlePlaceholder: "مثال: مناوبة ليلية — طوارئ",
    shiftStartsAt: "البداية",
    shiftEndsAt: "النهاية",
    hourlyRate: "الأجر بالساعة",
    notes: "ملاحظات",
    publishShift: "نشر المناوبة",
    shiftPublished: "تم نشر المناوبة",
    subExpiredShift: "النشر متوقف مؤقتاً لهذا الحساب — تواصل مع الدعم للمساعدة",
    quotaReachedShift: "وصلت حد المناوبات النشطة في النسخة التجريبية — أنهِ مناوبة قائمة للنشر من جديد",
    shiftTitleMin: "أدخل عنوان المناوبة",
    setTimes: "حدّد وقت البداية والنهاية",
    endAfterStart: "وقت النهاية يجب أن يكون بعد البداية",
    startInPast: "وقت البداية يجب أن يكون في المستقبل",
    tooLong: "مدة المناوبة الواحدة لا تتجاوز 24 ساعة — تحقق من التاريخ",
    hourlyRateRequired: "أدخل الأجر بالساعة",
    // Review step
    publishSteps: ["التفاصيل", "المراجعة", "النشر"],
    reviewCta: "مراجعة قبل النشر",
    reviewTitle: "راجع التفاصيل قبل النشر",
    reviewSub: "تأكد من صحة البيانات. يمكنك الرجوع والتعديل قبل النشر.",
    draftSaved: "تُحفظ المسودة تلقائياً على هذا الجهاز",
    privacyHint:
      "هوية المنشأة مخفية حتى تسمح بكشفها، لذا لا تكتب اسم المنشأة أو رقم هاتف أو واتساب أو بريداً أو رابط موقع داخل النص.",
    privacyReview: "سيُنشر النص دون اسم المنشأة أو أي وسيلة تواصل مباشرة.",
    privacyBlocked:
      "النص يحتوي على اسم المنشأة أو وسيلة تواصل مباشرة (رابط أو بريد أو رقم). احذفها ثم أعد المحاولة.",
    backToEdit: "رجوع وتعديل",
    confirmPublish: "تأكيد النشر",
    notSet: "غير محدد",
    none: "بدون",
    salaryRange: "نطاق الراتب",
    duration: (h: string) => `المدة: ${h} ساعة`,
    // Post-publish
    publishedTitle: "تم النشر بنجاح",
    publishedSubJob: "وظيفتك أصبحت مرئية للكوادر. تستطيع الآن دعوة مختصين مباشرة لها.",
    publishedSubShift: "مناوبتك أصبحت مرئية للكوادر. تستطيع الآن دعوة مختصين مباشرة لها.",
    inviteNow: "دعوة مختصين الآن",
    doneLater: "لاحقاً",
    inviteDialogTitle: "دعوة مختصين",
    workspace: "مساحة المنشأة",
    overview: "إدارة النشر والتوظيف من مكان واحد.",
    quickActions: "إجراءات مباشرة",
    createWork: "نشر عمل",
    createWorkText: "وظيفة أو مناوبة جديدة",
    candidates: "البحث عن مختصين",
    candidatesText: "ابحث وادعُ مختصين مناسبين",
    messagesText: "تابع المحادثات غير المقروءة",
    facilityProfile: "ملف المنشأة",
    facilityProfileText: "راجع البيانات والتوثيق",
    publishedWork: "أعمالك المنشورة",
    attention: "يحتاج انتباهك",
    overdueTitle: (n: number) => `${n} مناوبة انتهت وتحتاج إنهاء`,
    overdueBody: "سجّل انتهاء المناوبة لفتح التقييم وإكمال سجلها للطرفين.",
    reviewShifts: "مراجعة المناوبات",
    applicantsTitle: (n: number) => `${n} طلب جديد بانتظار المراجعة`,
    applicantsBody: "ابدأ من الفرصة المرتبطة لمراجعة المتقدمين واتخاذ الخطوة التالية.",
    reviewWork: "فتح الأعمال المنشورة",
    trialUsage: "حدود الاستخدام التجريبي",
    viewPublished: "عرض الفرصة",
  },
  en: {
    loading: "Loading...",
    verified: " · Verified facility",
    unverified: " · Verification pending",
    applicants: "Applicants",
    trial: "Free trial",
    expired: "Expired",
    endsAt: (d: string) => `Ends on ${d}`,
    activeSub: "Trial access available",
    activeJobsCount: (a: number, b: number) => `Active jobs ${a}/${b}`,
    activeShiftsCount: (a: number, b: number) => `Open shifts ${a}/${b}`,
    publish: "Publish opportunity",
    verifyNow: "Complete facility verification",
    verifyBody: "Upload the required documents so professionals can trust your verified facility badge.",
    newApplicants: "New applications",
    unreadMessages: "Unread messages",
    activeJobs: "Active jobs",
    openShifts: "Open shifts",
    searchesRemaining: (n: number) => `${n} searches remaining`,
    loadFailed: "We couldn't load your facility data.",
    retry: "Try again",
    tabJobs: (n: number) => `Jobs (${n})`,
    tabShifts: (n: number) => `Shifts (${n})`,
    tabNewJob: "Post a job",
    tabNewShift: "Post a shift",
    applicantsCount: (n: number) => `${n} applicants`,
    published: "Published",
    closed: "Closed",
    close: "Close",
    republish: "Republish",
    noJobs: "You haven't posted any jobs yet.",
    perHour: "/hr",
    open: "Open",
    bookedStatus: "Booked",
    noShifts: "No shifts posted.",
    view: "View",
    cancelledStatus: "Cancelled",
    cancelShift: "Cancel",
    shiftCancelled: "Shift cancelled",
    confirmCloseTitle: "Close this job?",
    confirmCloseDesc: "It will be hidden from seekers and stop receiving applications. You can republish later.",
    confirmCloseCta: "Yes, close it",
    confirmCancelShiftTitle: "Cancel this shift?",
    confirmCancelShiftDesc: "The shift will be cancelled and hidden from seekers. This cannot be undone.",
    confirmCancelBookedShiftDesc:
      "This shift is booked. Cancelling it will cancel the professional's booking and notify them. This cannot be undone.",
    confirmCancelShiftCta: "Yes, cancel it",
    moreActions: "More actions",
    tabAll: (n: number) => `All (${n})`,
    invite: "Invite professionals",
    confirmCompleteTitle: "Complete shift?",
    confirmCompleteDesc: "The shift will be marked completed and cannot be reverted.",
    confirmCompleteCta: "Complete shift",

    // Facility form
    registerTitle: "Register your facility",
    registerSub: "One minute and you can post your first job or shift.",
    facilityName: "Facility name",
    facilityType: "Facility type",
    hospital: "Hospital",
    clinic: "Clinic",
    polyclinic: "Polyclinic",
    pharmacy: "Pharmacy",
    lab: "Lab / Imaging",
    country: "Country",
    pickCountry: "Choose a country",
    city: "City",
    website: "Website",
    description: "About the facility",
    saving: "Saving...",
    createFacility: "Create facility profile",
    createdFacility: "Facility profile created",
    saveFailed: "Failed to save",
    nameRequired: "Enter the facility name",
    countryRequired: "Choose a country",
    cityRequired: "Enter the city",
    // Job form
    jobTitle: "Job title",
    specialty: "Specialty",
    pickSpecialty: "Choose a specialty",
    employmentType: "Employment type",
    minExperience: "Minimum experience required (years)",
    vacancies: "Open positions",
    vacanciesHint: "How many candidates do you want to hire? The job closes automatically once filled.",
    salaryFrom: "Salary from",
    salaryTo: "Salary to",
    currency: "Currency",
    requiredLicense: "Required license",
    licensePlaceholder: "None / choose a country",
    jobDesc: "Job description and requirements",
    publishing: "Publishing...",
    publishJob: "Post job",
    jobPublished: "Job posted",
    publishFailed: "Failed to publish",
    subExpiredJob: "Publishing is temporarily paused for this account — contact support for help",
    quotaReachedJob: "You've reached the trial's active job limit — close an active job to post again",
    titleMin: "Enter a job title",
    descMin: "Write a description of at least 20 characters",
    salaryMaxGt: "The maximum salary must be higher",
    // Shift form
    shiftTitle: "Shift title",
    shiftTitlePlaceholder: "e.g. Night shift — Emergency",
    shiftStartsAt: "Start",
    shiftEndsAt: "End",
    hourlyRate: "Hourly rate",
    notes: "Notes",
    publishShift: "Post shift",
    shiftPublished: "Shift posted",
    subExpiredShift: "Publishing is temporarily paused for this account — contact support for help",
    quotaReachedShift: "You've reached the trial's active shift limit — complete an existing shift to post again",
    shiftTitleMin: "Enter a shift title",
    setTimes: "Set the start and end time",
    endAfterStart: "End time must be after start time",
    startInPast: "Start time must be in the future",
    tooLong: "A single shift can't exceed 24 hours — check the date",
    hourlyRateRequired: "Enter the hourly rate",
    // Review step
    publishSteps: ["Details", "Review", "Publish"],
    reviewCta: "Review before publishing",
    reviewTitle: "Review the details before publishing",
    reviewSub: "Check everything is correct. You can go back and edit before publishing.",
    draftSaved: "Draft saves automatically on this device",
    privacyHint:
      "Your facility identity stays hidden until you reveal it, so don't include the facility name, a phone or WhatsApp number, an email, or a website in the text.",
    privacyReview: "This will publish without your facility name or any direct contact details.",
    privacyBlocked:
      "The text includes your facility name or a direct contact detail (link, email, or number). Remove it and try again.",
    backToEdit: "Back to edit",
    confirmPublish: "Confirm and publish",
    notSet: "Not set",
    none: "None",
    salaryRange: "Salary range",
    duration: (h: string) => `Duration: ${h} hours`,
    // Post-publish
    publishedTitle: "Published successfully",
    publishedSubJob: "Your job is now visible to professionals. You can invite specialists directly.",
    publishedSubShift: "Your shift is now visible to professionals. You can invite specialists directly.",
    inviteNow: "Invite professionals now",
    doneLater: "Later",
    inviteDialogTitle: "Invite professionals",
    workspace: "Facility workspace",
    overview: "Manage publishing and hiring in one place.",
    quickActions: "Direct actions",
    createWork: "Publish work",
    createWorkText: "Create a job or shift",
    candidates: "Find professionals",
    candidatesText: "Search and invite suitable professionals",
    messagesText: "Continue unread conversations",
    facilityProfile: "Facility profile",
    facilityProfileText: "Review details and verification",
    publishedWork: "Published work",
    attention: "Needs your attention",
    overdueTitle: (n: number) => `${n} ended shift(s) need completion`,
    overdueBody: "Complete each shift to unlock reviews and close its record for both sides.",
    reviewShifts: "Review shifts",
    applicantsTitle: (n: number) => `${n} new application(s) await review`,
    applicantsBody: "Open the related opportunity to review candidates and take the next step.",
    reviewWork: "Open published work",
    trialUsage: "Trial usage limits",
    viewPublished: "View opportunity",
  },
} as const;

export type PlanRow = {
  code: string;
  name_ar: string;
  active_jobs: number;
  active_shifts: number;
  candidate_searches: number;
  ai_credits: number;
  is_trial: boolean;
};
export type SubRow = {
  status: string;
  ends_at: string | null;
  plan_code: string;
  searches_used: number;
  subscription_plans: PlanRow | null;
};

/** رسائل واضحة بدل أكواد قاعدة البيانات. */
export function shiftErrorText(raw: string, lang: "ar" | "en") {
  if (raw.includes("SHIFT_FINAL_STATE") || raw.includes("INVALID_SHIFT_TRANSITION"))
    return lang === "ar" ? "لا يمكن تغيير حالة هذه المناوبة بعد الآن." : "This shift's status can no longer change.";
  if (raw.includes("SHIFT_NOT_COMPLETABLE"))
    return lang === "ar"
      ? "لا يمكن إنهاء المناوبة إلا بعد انتهاء وقتها وكونها محجوزة."
      : "A shift can only be completed once it is booked and its time has passed.";
  if (raw.includes("SHIFT_HAS_ACTIVE_BOOKING"))
    return lang === "ar"
      ? "هذه المناوبة محجوزة — ألغِ الحجز أولاً ثم ألغِ المناوبة."
      : "This shift is booked — cancel the booking first, then cancel the shift.";
  if (raw.includes("SHIFT_BOOKING_INVARIANT"))
    return lang === "ar"
      ? "حالة المناوبة لا تطابق حجوزاتها، حدّث الصفحة وحاول مجدداً."
      : "The shift status doesn't match its bookings. Refresh the page and try again.";
  if (raw.includes("SHIFT_NOT_FOUND"))
    return lang === "ar" ? "لم نعد نجد هذه المناوبة." : "We couldn't find this shift.";
  if (raw.includes("FORBIDDEN"))
    return lang === "ar" ? "هذا الإجراء متاح لمالك المنشأة فقط." : "Only the facility owner can do this.";
  return lang === "ar" ? "تعذّر إتمام الإجراء، حاول مرة أخرى." : "We couldn't complete that action. Please try again.";
}

