import React, { useState } from "react";
import { FlatList, Pressable, RefreshControl, ScrollView, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { CalendarClock, MapPin, Search } from "lucide-react-native";
import { Badge, Card, Chip, EmptyState, ErrorState, Loading, Row, styles as ui } from "@/components/ui";
import { Brand } from "@/components/brand";
import { useI18n } from "@/lib/i18n";
import { useShiftSearch, useSpecialties, type ShiftRow } from "@/lib/queries";
import { formatDateTime, formatMoney } from "@/lib/format";
import { userMessage } from "@/lib/errors";
import { colors, radii } from "@/lib/theme";

export default function ShiftsTab() {
  const { t, lang } = useI18n(); const router = useRouter(); const [q, setQ] = useState(""); const [term, setTerm] = useState(""); const [specialtyId, setSpecialtyId] = useState<string | null>(null); const specialties = useSpecialties(); const shifts = useShiftSearch({ q: term, specialtyId });
  return <SafeAreaView edges={["top"]} style={{ flex: 1, backgroundColor: colors.bg }}><View style={{ paddingHorizontal: 18, paddingTop: 10, gap: 14 }}><View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}><Brand compact/><View><Text style={ui.title}>{t("shifts")}</Text><Text style={ui.muted}>{lang === "ar" ? "مناوبات متاحة بوقت واضح" : "Available shifts at a glance"}</Text></View></View><View style={{ flexDirection: "row", alignItems: "center", gap: 9, minHeight: 52, paddingHorizontal: 14, borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }}><Search size={20} color={colors.textMuted}/><TextInput value={q} onChangeText={setQ} onSubmitEditing={() => setTerm(q.trim())} returnKeyType="search" placeholder={t("searchShifts")} placeholderTextColor={colors.textSubtle} style={[ui.input, { flex: 1, borderWidth: 0, backgroundColor: "transparent", paddingHorizontal: 0 }]}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}><Chip label={t("all")} active={!specialtyId} onPress={() => setSpecialtyId(null)}/>{(specialties.data ?? []).map((s) => <Chip key={s.id} label={lang === "ar" ? s.name_ar : s.name_en || s.name_ar} active={specialtyId === s.id} onPress={() => setSpecialtyId(specialtyId === s.id ? null : s.id)}/>)}</ScrollView></View>
    {shifts.isPending ? <Loading/> : shifts.isError ? <View style={{ padding: 18 }}><ErrorState message={userMessage(shifts.error, lang)} onRetry={() => void shifts.refetch()}/></View> : <FlatList data={(shifts.data ?? []) as ShiftRow[]} keyExtractor={(item) => item.id} contentContainerStyle={{ padding: 18, gap: 12, paddingBottom: 110 }} refreshControl={<RefreshControl refreshing={shifts.isFetching} onRefresh={() => void shifts.refetch()}/>} ListEmptyComponent={<EmptyState text={t("emptyShifts")}/>} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/shift/[id]", params: { id: item.id } })}><Card><View style={{ flexDirection: "row", gap: 12 }}><View style={{ width: 46, height: 46, borderRadius: radii.md, backgroundColor: colors.accentSoft, alignItems: "center", justifyContent: "center" }}><CalendarClock size={22} color={colors.accent}/></View><View style={{ flex: 1, gap: 4 }}><Row gap={7} wrap><Text style={[ui.bodyStrong, { flexShrink: 1 }]}>{item.title}</Text>{item.is_urgent ? <Badge label={lang === "ar" ? "عاجلة" : "Urgent"} tone="warning"/> : null}</Row><Text style={ui.muted}>{formatDateTime(item.starts_at, lang)}</Text></View></View><Row gap={6} wrap><MapPin size={14} color={colors.textMuted}/><Text style={ui.muted}>{item.city} · {item.country}</Text><Badge label={`${formatMoney(item.hourly_rate, item.currency, lang)} / ${lang === "ar" ? "ساعة" : "hr"}`} tone="primary"/></Row></Card></Pressable>} />}
  </SafeAreaView>;
}